spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://circleguard-postgres:5432/circleguard_auth}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  ldap:
    urls: ${SPRING_LDAP_URLS:ldap://circleguard-ldap:389}
    base: ${SPRING_LDAP_BASE:dc=circleguard,dc=edu}
    username: ${SPRING_LDAP_USERNAME:cn=admin,dc=circleguard,dc=edu}
    password: ${SPRING_LDAP_PASSWORD:admin}

jwt:
  secret: ${JWT_SECRET:my-super-secret-dev-key-32-chars-long-12345678}
  expiration: ${JWT_EXPIRATION:3600000}

qr:
  secret: ${QR_SECRET:my-qr-secret-key-for-dev-1234567890}
  expiration: ${QR_EXPIRATION:300}
